### ISSUE TITLE
-[__NSCFString charValue]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by allran** [dcty/YYJSON#4]
newArr = [list toModels:[GoodsBaseInfo class]];
处理时，出现bug。

其中：
@protocol GoodsBaseInfo <NSObject>
@end
@interface GoodsBaseInfo : NSObject
@property(nonatomic,assign) int                     goodsid;          //商品id
@property(nonatomic,strong) NSString*               name;          //商品标题
@property(nonatomic,strong) NSString*               brief;           //商品简介
@property(nonatomic,strong) NSString*               thumb;          //商品封面url
@property(nonatomic,strong) NSString*               img;          //商品实际图片
@property(nonatomic,assign) double                  price;          //价格
@property(nonatomic,assign) BOOL                    is_hot;          //是否热卖（选项）
@property(nonatomic,assign) BOOL                    is_promote;          //是否为预购产品(0不是， 1是)
@property(nonatomic,assign) BOOL                    is_seasonal;          //是否为季节性的（选项）
@end

![2015-02-25 11 45 13](https://cloud.githubusercontent.com/assets/1505892/6364612/d16e069c-bce3-11e4-9672-93739e5da6dd.png)

对象化的数据为如下所示：
![2015-02-25 11 47 20](https://cloud.githubusercontent.com/assets/1505892/6364643/485164f2-bce4-11e4-828e-87b7a46d202b.png)

**Comment by dcty** [comment]
麻烦把 operation.responseString 发上来一下，这个问题应该是数据格式出问题了。

**Comment by dcty** [comment]
is_seasonal，服务端返回的是字符串类型，你让服务端返回bool类型即可，
